version: '3.8'
 
services:
  postgres_db:
    image: postgres:16-alpine
    container_name: classboard_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-tu_contraseña_segura}
      POSTGRES_DB: ${DB_NAME:-classboard_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
 
volumes:
  postgres_data:
 